### ISSUE TITLE
Not working on Node V6 (T7318)

### ISSUE THREAD

**Issue by danez** [danez/test-import#1]
> Issue originally made by @RoberMac

### Bug information

* **Babel version:** v6.7.7
* **Node version:** v6.0.0
* **npm version:** v3.8.6

### Input code

```js
NODE_ENV=production webpack --config webpack.config.prod.js -p --progress --colors
 95% emit
WebpackCleanupPlugin: 3 file(s) deleted.
Hash: 07d3392aeddf699c65bc
Version: webpack 1.13.0
Time: 48572ms
                         Asset       Size  Chunks             Chunk Names
common.07d3392aeddf699c65bc.js  204 bytes       0  [emitted]  common
    + 2 hidden modules

ERROR in ./public/js/entry/app.js
Module build failed: Error: Cannot find module 'core-js/library/fn/get-iterator'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/XXX/Desktop/XXX/node_modules/babel-preset-react/node_modules/babel-plugin-transform-react-jsx/node_modules/babel-helper-builder-react-jsx/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-runtime/core-js/get-iterator.js:1:93)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/XXX/Desktop/XXX/node_modules/babel-preset-react/node_modules/babel-plugin-transform-react-jsx/node_modules/babel-helper-builder-react-jsx/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/lib/index.js:5:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/XXX/Desktop/XXX/node_modules/babel-preset-react/node_modules/babel-plugin-transform-react-jsx/node_modules/babel-helper-builder-react-jsx/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/lib/index.js:469:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/XXX/Desktop/XXX/node_modules/babel-preset-react/node_modules/babel-plugin-transform-react-jsx/node_modules/babel-helper-builder-react-jsx/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/node_modules/babel-types/node_modules/babel-traverse/lib/path/lib/virtual-types.js:7:19)
    at Module._compile (module.js:541:32)
```

**Comment by danez** [comment]
> Comment originally made by paulyoung on 2016-03-08T18:41:04.000Z

sebmck I heard about this today and was wondering if Babel was considering adding a similar polyfill.

https://github.com/GoogleChrome/proxy-polyfill

**Comment by danez** [comment]
> Comment originally made by Derek Greer (derekgreer) on 2016-02-16T16:21:59.000Z

Just to clarify, was the decision to have "use strict" inserted at the top of the file or within the module?  It sounded like the decision was that it should be within the module, but as of version 6.5.2 with the strict plugin, I'm seeing it inserted at the top of the file.

**Comment by danez** [comment]
> Comment originally made by Alec Larson (aleclarson) on 2016-05-27T18:15:12.000Z

sebmck What do I need to change in my `.babelrc` to have `esformatter` run on each transformed file?

**Comment by danez** [comment]
> Comment originally made by mdreizin on 2016-04-06T23:33:07.000Z

Any updates about that issue?

`babel-node` with `sourceMap: 'inline'` generates unusable `sourcemap` that prevents to debug your code.

https://youtrack.jetbrains.com/issue/WEB-19159
https://youtrack.jetbrains.com/issue/WEB-21133

**Comment by danez** [comment]
> Comment originally made by luxp on 2016-08-15T16:22:44.000Z

I test it in IE8, this seems not work for me.
I added babel-polyfill6.13.0.
```
var nodeList = document.querySelectorAll('span');
for(let  node of nodeList) {
  node.style.color = '#DD2727';
}
```
And I transformed it use  [babeljs/repl]( https://babeljs.io/repl)

The result is below
```
'use strict';

var nodeList = document.querySelectorAll('span');

for (var _iterator = nodeList, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
    var _ref;

    if (_isArray) {
        if (_i >= _iterator.length) break;
        _ref = _iterator[_i++];
    } else {
        _i = _iterator.next();
        if (_i.done) break;
        _ref = _i.value;
    }

    var node = _ref;

    node.style.color = '#DD2727';
}
```

But this didn't work in IE8.

You can test it using the code below
```
<style>
    span {
        margin-right: 10px;
    }
</style>
<script src="//cdn.bootcss.com/babel-polyfill/6.13.0/polyfill.js"></script>
<span>Rock</span><span>the</span><span>World!</span>
<script>
    'use strict';

    var nodeList = document.querySelectorAll('span');

    for (var _iterator = nodeList, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
        var _ref;

        if (_isArray) {
            if (_i >= _iterator.length) break;
            _ref = _iterator[_i++];
        } else {
            _i = _iterator.next();
            if (_i.done) break;
            _ref = _i.value;
        }

        var node = _ref;

        node.style.color = '#DD2727';
    }
</script>

```
I found out of the problem is ` _iterator[Symbol.iterator]()`;
And I solved this problem by transfroming the nodeList to Array before using for ...of.
```
<style>
    span {
        margin-right: 10px;
    }
</style>
<script src="//cdn.bootcss.com/babel-polyfill/6.13.0/polyfill.js"></script>
<span>Rock</span><span>the</span><span>World!</span>
<script>
    'use strict';

    var nodeList = document.querySelectorAll('span');
    
   // add this line.
    nodeList = Array.prototype.slice.call(nodeList);
    
    for (var _iterator = nodeList, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
        var _ref;

        if (_isArray) {
            if (_i >= _iterator.length) break;
            _ref = _iterator[_i++];
        } else {
            _i = _iterator.next();
            if (_i.done) break;
            _ref = _i.value;
        }

        var node = _ref;

        node.style.color = '#DD2727';
    }
</script>
```

**Comment by danez** [comment]
> Comment originally made by thejameskyle on 2015-11-20T19:27:49.000Z

I'm pretty sure this can be closed.

**Comment by danez** [comment]
> Comment originally made by thejameskyle on 2015-11-20T19:30:26.000Z

Marking this as low priority for now.

> Comment originally made by bergus on 2016-08-26T00:51:46.000Z

I think you should raise the priority of this issue. `new.target` is not transpiled at all currently, which does raise a syntax error in ES5.

See also [this StackOverflow question](http://stackoverflow.com/questions/39155082/babeljs-class-static-in-constructor). It seems like it was supported in Babel 5, is that correct?

**Comment by danez** [comment]
> Comment originally made by phpnode on 2015-12-03T22:38:30.000Z

sebmck loganfsmyth flow now supports `export interface`, as of https://github.com/facebook/flow/pull/1145 please can we reopen this issue?

> Comment originally made by loganfsmyth on 2015-12-04T01:10:49.000Z

phpnode Feels worth opening a new issue since this is a feature request rather than a bug at this point.
